---
title: "HW2_VanCraeynest_Vanhauwe"
author: "Toon Vancraeynest, Jonas Vanhauwe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(coin)
library(extraDistr) #Laplace distribution
library(ggplot2) #Plotting barplots
```

## Q1
```{r, echo=TRUE}
#Code written by Toon
median.test.two_sided <- function(vec1, vec2, N=1000, exact=FALSE) {
  # Calculate observed test statistic
  observed_test_statistic <- abs(median(vec1) - median(vec2))
  
  # Combine both vectors
  full_vec <- c(vec1, vec2)
  
  # Check if the number of combinations is less than 10,000
  if (choose(length(full_vec), length(vec1)) < N | exact) {
    
    # Generate the null distribution by exact combinations
    t_star <- combn(length(full_vec), length(vec1), function(x) {
      group1 <- full_vec[x]
      group2 <- full_vec[-x]  # all elements not in x
      test_stats <- abs(median(group1) - median(group2))
      test_stats
    })
  } else {
    
    #message("Using approximation method with 10,000 random permutations.")
    
    # Approximate null distribution by permutation if combinations exceed 10,000
    #N <- 500
    Groupvec <- c(rep(1, length(vec1)), rep(2, length(vec2)))  # Create group vector
    perm_data <- data.frame(value = full_vec, group = Groupvec)  # Create data frame for permutations
    t_star <- replicate(N, {
      # Shuffle the group labels:
      perm_data$group <- sample(perm_data$group)
      # Calculate the test statistic for shuffled groups:
      test_stats <- abs(median(perm_data$value[perm_data$group == 1]) - median(perm_data$value[perm_data$group == 2]))
      test_stats
    })
  }
  
  # Calculate the p-value
  p_value <- mean(t_star >= observed_test_statistic)
  
  p_value
}
```

## Q2

```{r, include=TRUE, cache=TRUE, echo=TRUE}
#Code written by Toon
set.seed(100) #For reproductibility
nsim <- 500
#t3 distribution
p.t <- p.wmw <- p.med <- numeric(nsim) #empty vector of p values for each test
n <- 20 # n observations in each group
#variance t-distribution = dof/(dof-2)
#with dof the degrees of freedom
delta <- sqrt(3)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- rt(n, 3)
  Y2 <- rt(n, 3) + delta
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  #Wilcoxon-Mann-Whitney test
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  #median test
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
# Monte-Carlo approximation of the power
# for alpha = .05
c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))
```

## Power of tests for different distributions

```{r, power_exponential, cache=TRUE}
#Code written by Jonas
#Store power of different distributions for these tests in a list
output <- list()
#append power of tests for t3 distribution
output <- append(output, list(t3_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))

#Exponential distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
#variance = 1/rate**2
delta <- sqrt(1)/2 #delta = sqrt(variance)/2
for (i in 1:nsim) {
  Y1 <- rexp(n, rate = 1)
  Y2 <- rexp(n, rate = 1)+delta
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2, exact=TRUE)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}

#Append power of test for exponential distribution
output <- append(output, list(exp_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, power_laplace, cache=TRUE}
#Laplace distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
# variance = 2*sigma**2
delta <- sqrt(2)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- rlaplace(n, mu = 0, sigma = 1)
  Y2 <- rlaplace(n, mu = delta, sigma = 1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append power of test for laplace distribution
output <- append(output, list(laplace_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, power_t5, cache=TRUE}
#t5 distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
#variance t-distribution = dof/(dof-2)
#with dof the degrees of freedom
delta <- sqrt(5/3)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- rt(n, 5)
  Y2 <- rt(n, 5) + delta
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}

#Append power of test for t5 distribution
output <- append(output, list(t5_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, power_logistic, cache=TRUE}
#Logistic distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
#variance = scale**2 * pi**2 / 3 
delta <- sqrt(pi**2/3)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- rlogis(n, location=0, scale=1)
  Y2 <- rlogis(n, location = delta, scale=1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append power of test for logistic distribution
output <- append(output, list(logistic_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, power_normal, cache=TRUE}
#normal distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
#variance = sqrt(sigma)
delta <- sqrt(1)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- rnorm(n, 0, 1)
  Y2 <- rnorm(n, delta, 1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append power of test for normal distribution
output <- append(output, list(normal_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, power_uniform, cache=TRUE}
#uniform distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
#variance = 1/12 * (max-min)**2
delta <- sqrt(1/12)/2 #delta = sqrt(variance)/2
for(i in 1:nsim)
{
  Y1 <- runif(n, min=0, max=1)
  Y2 <- runif(n, min=0, max=1)+delta
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append power test for uniform distribution
output <- append(output, list(uniform_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r}
# create a dataset from this list
distributions <- rep(c("t3", "Exponential", "Laplace", "t5", "Logistic", "Normal", "Uniform"), each=3) #
tests <- rep(c("permutation t" , "wilcox" , "median") , 7)
power <- unlist(output)
data <- data.frame(distributions,tests,power)

# Grouped barplot
ggplot(data, aes(fill=tests, y=power, x=distributions)) + 
  geom_bar(position="dodge", stat="identity") + coord_flip()
```

## Type I error rate of tests for different distributions
```{r, typeI_t3, cache=TRUE}
set.seed(100)
nsim <- 500
#Store Type I error rate of different distributions for these tests in a list
output2 <- list()

#t3 distribution
p.t <- p.wmw <- p.med <- numeric(nsim) #empty vector of p values for each test
n <- 20 # n observations in each group
for(i in 1:nsim)
{
  Y1 <- rt(n, 3)
  Y2 <- rt(n, 3)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  #Wilcoxon-Mann-Whitney test
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  #median test
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
# Monte-Carlo approximation of the power
# for alpha = .05
#append Type I error rate for t3 distribution
output2 <- append(output2, list(t3_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```

```{r, typeI_exponential, cache=TRUE}
#Exponential distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
for (i in 1:nsim) {
  Y1 <- rexp(n, rate = 1)
  Y2 <- rexp(n, rate = 1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2, exact=TRUE)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}

#Append Type I error rate for exponential distribution
output2 <- append(output2, list(exp_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, typeI_laplace, cache=TRUE}
#Laplace distribution
p.t <- p.wmw <- p.med <- numeric(nsim)

for(i in 1:nsim)
{
  Y1 <- rlaplace(n, mu = 0, sigma = 1)
  Y2 <- rlaplace(n, mu = 0, sigma = 1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append Type I error rate for laplace distribution
output2 <- append(output2, list(laplace_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, typeI_t5, cache=TRUE}
#t5 distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
for(i in 1:nsim)
{
  Y1 <- rt(n, 5)
  Y2 <- rt(n, 5)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}

#Append Type I error rate for t5 distribution
output2 <- append(output2, list(t5_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, typeI_logistic, cache=TRUE}
#Logistic distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
for(i in 1:nsim)
{
  Y1 <- rlogis(n, location=0, scale=1)
  Y2 <- rlogis(n, location = 0, scale=1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append Type I error rate for logistic distribution
output2 <- append(output2, list(logistic_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, typeI_normal, cache=TRUE}
#normal distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
for(i in 1:nsim)
{
  Y1 <- rnorm(n, 0, 1)
  Y2 <- rnorm(n, 0, 1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append Type I error rate for normal distribution
output2 <- append(output2, list(normal_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r, typeI_uniform, cache=TRUE}
#uniform distribution
p.t <- p.wmw <- p.med <- numeric(nsim)
for(i in 1:nsim)
{
  Y1 <- runif(n, min=0, max=1)
  Y2 <- runif(n, min=0, max=1)
  X <- factor(c(rep("A",n),rep("B",n)))
  Y <- c(Y1, Y2)
  #permutation t-test
  p.t[i] <- pvalue(oneway_test(Y ~ X,
                               distribution=approximate(nresample=1000)))
  p.wmw[i] <- wilcox.test(Y1,Y2)$p.value
  p.med[i] <- median.test.two_sided(Y1, Y2)
}
#Append Type I error rate for uniform distribution
output2 <- append(output2, list(uniform_distribution=c(mean(p.t<0.05), mean(p.wmw<0.05), mean(p.med<0.05))))
```
```{r}
# create a dataset from this list
#Names of the distributions
distributions <- rep(c("t3", "Exponential", "Laplace", "t5", "Logistic", "Normal", "Uniform"), each=3)
#Names of the tests
tests <- rep(c("permutation t" , "wilcox" , "median") , 7)
#Type I error rate
typeI <- unlist(output2)
data <- data.frame(distributions,tests,typeI)

# Grouped barplot
ggplot(data, aes(fill=tests, y=typeI, x=distributions)) + 
  geom_bar(position="dodge", stat="identity") + geom_hline(yintercept = 0.05, color = "red", linetype = "dashed", linewidth = 1) + coord_flip()
```

## Appendix

```{r getlabels, echo = FALSE}
labs = c("power_exponential", "power_laplace", "power_t5", "power_logistic", "power_normal", "power_uniform", "typeI_t3", "typeI_exponential", "typeI_laplace", "typeI_t5", "typeI_logistic", "typeI_normal", "typeI_uniform")
```

```{r allcode, ref.label = labs, echo=TRUE, eval = FALSE}
```






